
/** I HERE WANT A BETTER WAY TO  LOAD DATA INSTEAD OF MESSY AMIN FUNCTION DATA CAN DEFINATE;Y LIVE INSIDE A TXT FILE
 * OR COULD BE IN  CSV ,JSON BUT THE THE MAIN CONCERN IS DYNAMICALLY REALOADING DATA INSTEAD OF  CHANGING MAIN CODE
 * JSON LOOKS A GOOD CHOICE HERE
 */
